### ISSUE TITLE
Inertia Testing Fails in GitHub Actions Due to Laravel 12 and Starter Kit Structure

### ISSUE THREAD

**Issue by rdehnhardt** [inertiajs/inertia-laravel#718]
**Description**

With the new Laravel 12 version, Inertia's testing configuration variable `inertia.testing.view-finder` defaults to `resource_path('js/Pages')`. However, the latest starter kits use the `js/pages` directory structure.

This discrepancy causes tests to fail in GitHub Actions, even though they pass locally.

**Steps to Reproduce**

1.  Create a new Laravel 12 project using a starter kit with Inertia and React.
2.  Run tests locally (`./vendor/bin/pest or php artisan test`). (Tests pass)
3.  Commit and push the changes to a GitHub repository with GitHub Actions configured to run tests.
4.  Observe the test failure in GitHub Actions:

    ```
    FAILED  Tests\Feature\Auth\LoginTest > it can render the login screen
    AssertionFailedError
    Inertia page component file [auth/login] does not exist.
    at vendor/inertiajs/inertia-laravel/src/Testing/AssertableInertia.php:63
    ```

**Expected Behavior**

Tests should pass in both local and GitHub Actions environments without requiring manual configuration changes.

**Actual Behavior**

Tests fail in GitHub Actions due to the `inertia.testing.view-finder` configuration mismatch.

**Possible Cause**

The default `inertia.testing.view-finder` configuration in Laravel 12 does not align with the directory structure used by the latest starter kits.

**Additional Information**

* Laravel version: 12
* Inertia version: 2
* Starter Kit: React

**Possible Solutions**

* Update the default `inertia.testing.view-finder` configuration in Laravel 12 to match the starter kit structure.
* Update the starter kits to use the `resource_path('js/Pages')` directory structure.
* Provide clear documentation on how to configure `inertia.testing.view-finder` when using starter kits with Laravel 12.

**Environment details**

* Local Environment: MacOS
* Github Actions: ubuntu-latest

**Comment by rdehnhardt** [comment]
This is the test YML. I've made a few adjustments attempting to resolve the issue, but it largely mirrors the default setup from `laravel new app`.

```yaml
name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: npm run build

      - name: Tests
        run: php artisan test
```
